#!/bin/csh -f

if ($#argv < 2 || $#argv > 3) then
    echo "Usage: $0 <design_tree> <normalize_table> [module]"
    exit 1
endif

set design_script = "gen_design_tree_xls2flow.py"
set dft_script = "gen_dft_sig_xls2flow.py"
set cfg_script = "gen_cfg.py"

set design_tree = "$1"
set normalize_table = "$2"

if ($#argv == 3) then
    set module = "$3"
    set cfg_args = "-modules $module"
else
    set cfg_args = "-all"
endif

foreach script ($design_script $dft_script $cfg_script)
    if (! -e $script) then
        echo "Error: Script '$script' not found!"
        exit 1
    endif
end

$design_script $design_tree
$dft_script $normalize_table
$cfg_script $normalize_table $cfg_args
