#!/bin/csh

set log_path = "$project_path/logs/$module"
if (! -e $log_path) then
    mkdir -p $log_path
endif

set step = $1
set cfg_file = "$project_path/configs/$module.cfg"
set log_file = "$log_path/$step.log"
set dsub = `alias dsubrun_I`
if ("$dsub" == "") then
    alias dsubrun_I ""
endif

if ($step == "create_project") then
    dsubrun_I dftv $step -cfg $cfg_file
else if ($step == "gen_design_info") then
    # sed -i ...
    dsubrun_I dftv $step -cfg $cfg_file | & tee $log_file
    sleep 1s
else
    dsubrun_I dftv $step -cfg $cfg_file | & tee $log_file
endif
