#!/bin/csh -f

set log_path = "$project_path/sailor/work/$module/log"
if (! -e $log_path) then
    mkdir -p $log_path
endif

set step = $1
set cfg_file = "$project_path/sailor/cfg/$module/$module.sailor.cfg"
set log_file = "$log_path/$step.log"
set dsub = `alias dsubrun_I`
if ("$dsub" == "") then
    alias dsubrun_I ""
endif

if ($step == "create_project") then
    dsubrun_I ddf $step -cfg $cfg_file
else if ($step == "gen_design_info") then
    # sed -i ...
    dsubrun_I ddf $step -cfg $cfg_file | & tee $log_file
    sleep 1s
else
    dsubrun_I ddf $step -cfg $cfg_file | & tee $log_file
endif
